#! /bin/sh

# wmnae, "error": "Remote control is disabled. Add allow_remote_control to your kitty.conf"}e i3 &
wal -i /home/b/Backgrounds/wp2570990-background-full-hd.jpg &
pgrep polybar || polybar topright &
pgrep polybar || polybar topleft &
#picom &
#/home/b/.config/polybar/launch.sh &
sleep 5 && deluge-gtk &
nm-applet &
xset s off -dpms
xset s off
thunar --daemon &
dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap          12
bspc config focused_border_color '#8acbdb'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a carla-bridge-win64.exe state=floating

bspc rule -a QjackCtl state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a origin.exe state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify state=floating
#bspc config focus_follows_pointer true
